### ISSUE TITLE
国产手机都不可以

### ISSUE THREAD

**Issue by xionger0520** [xiong-it/AutoInputAuthCode#10]
貌似国产手机都读取不到验证码信息吧 真正的作用不大

**Comment by xionger0520** [comment]
而且如果我只想拿到验证码信息  不需要填到EditText里面  应该怎么写？
demo太绝对了

**Comment by xionger0520** [comment]
应该给个回调啊 大神

**Comment by xiong-it** [comment]
`AuthCode.getInstance().with(context).config(config).into(EditText);`。into(EditText)会自动填入验证码。不过由于国产手机现状都做了短信与通知短信的权限区分，无法正确读库，此项目无限期关闭，请勿用于线上项目。
