### ISSUE TITLE
短信中有验证码和电话号码，取回的数是电话号码,请问怎么解决啊？感谢开源

### ISSUE THREAD

**Issue by fangxiaogang** [xiong-it/AutoInputAuthCode#4]

**Comment by xiong-it** [comment]
验证码的获取，实质上是正则表示式的截取，具体实现在authcode/src/main/java/tech/michaelx/authcode/ReadSmsService.java中285行实现，去除gradle远程依赖，下载本项目源码，使用源码moudule依赖的方式，修改源码为：
```
while (matcher.find()) {
    smsCode = matcher.group(1); // 跳过0角标的手机号码，获取第二个匹配到的4位数验证码，最好加一个catch异常。
}
```
后续笔者也会更新远程版本。
